### ISSUE TITLE
Saran untuk upgrade ke laravel 5.8 dan menambahkan readme yang lengkap.

### ISSUE THREAD

**Issue by ibnujakaria** [LendisFabri/Ringgo-Naive-Bayes-System#1]

**Comment by renbooo** [comment]
isu ditutup karna program masih broken

**Comment by ibnujakaria** [comment]
wah wah, menutup issue dengan cara yang tidak berpri-laravel-an sekali

**Comment by renbooo** [comment]
hahaha saya menutup issue dengan cara yang berpri-code-igniter-an sekali

**Comment by renbooo** [comment]
saya buka kembali issue nya :v

**Comment by ibnujakaria** [comment]
L6 :V

**Comment by ibnujakaria** [comment]
L7 :V

**Comment by renbooo** [comment]
L8 Waiting for you.... :v

**Comment by ibnujakaria** [comment]
Wowww di close lagi bung

**Comment by renbooo** [comment]
wah sekarang Anda lebih suka perang di github ya :v

**Comment by renbooo** [comment]
saya mau buat lampu lalu lintas mas :v
